title: Michelle Min
url: "https://michelle1223.github.io"
baseurl: "/researcher"

markdown: kramdown
ins_logo: "./ins-logo.png"
#favicon_location: "./assets/favicon.ico/"

tracking_id: #

footer: yes
footer_url: "https://github.com/michelle1223"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"

analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-3H9H1G234Y"
    anonymize_ip         : # true, false (default)
